# Genelis FAQ data and FAQPage schema generator


def section(heading, intro, cta_heading, cta_text, cta_button, cta_link_key, items):
    return {
        "heading": heading,
        "intro": intro,
        "cta_heading": cta_heading,
        "cta_text": cta_text,
        "cta_button": cta_button,
        "cta_link_key": cta_link_key,
        "items": [{"question": q, "answer": a} for q, a in items],
    }


FAQ_DATA = {}

FAQ_DATA["home"] = section(
    "Frequently Asked Questions",
    "Whether you're exploring Genelis for the first time or comparing different study platforms, here are answers to some of the most common questions about how Genelis works, who it is designed for, and how it helps students build stronger learning habits through one connected AI-powered learning experience.",
    "Still have questions?",
    "Experience how the Genelis Learning System brings together learning, practice, testing, analysis, and revision into one connected AI-powered learning experience.",
    "Start Learning",
    "start_learning",
    [
        ("What is Genelis?", "Genelis is an AI-powered learning platform designed for CBSE students in Classes 9 to 12. It brings together AI-generated notes, chapter-wise practice, mock tests, personalised performance insights, revision tools, and guided learning within a single connected workspace. At the heart of the platform is the Genelis Learning System, a structured approach that helps students learn, practise, test, analyse, improve, and reinforce their understanding instead of studying in disconnected steps. The goal is not just to help students prepare for exams, but to help them build stronger concepts and develop consistent learning habits throughout the academic year."),
        ("Who is Genelis designed for?", "Genelis is built primarily for CBSE students in Classes 9, 10, 11, and 12. Whether a student is preparing for school examinations, board exams, or looking for a more organised way to study, the platform adapts to different stages of preparation. Parents and educators can also use Genelis to support students by providing structured learning resources, personalised recommendations, and meaningful insights into academic progress."),
        ("Which classes does Genelis support?", "Genelis currently supports CBSE Classes 9, 10, 11, and 12 across major academic subjects aligned with the latest NCERT curriculum. Students can study chapter-wise, generate AI-powered notes, practise topic-specific questions, attempt mock tests, monitor their performance, and revisit difficult concepts using features such as the Wrong Question Notebook and Weak Area Detection, helping them focus revision where it matters most."),
        ("Is Genelis aligned with the latest CBSE and NCERT curriculum?", "Yes. Genelis is designed around the latest available CBSE curriculum and NCERT textbooks. Learning resources, AI-generated notes, practice material, and mock tests are regularly reviewed and updated to reflect curriculum changes. As official syllabus revisions are announced, the platform aims to incorporate those updates so students continue learning with content that remains relevant and aligned with current academic requirements."),
        ("How does AI improve the learning experience?", "Rather than replacing traditional learning, Artificial Intelligence helps personalise it. Within Genelis, AI assists students by generating structured notes, simplifying complex concepts, identifying weaker topics, recommending revision priorities, and providing performance insights based on learning behaviour. Combined with the Genelis Learning System and the AI Study Coach, these features help students understand what to study next instead of simply giving them more content."),
        ("Is Genelis free to use?", "Yes. Genelis offers a Free Plan that allows students to explore the platform and experience its core learning features before upgrading. Students who need higher usage limits, unlimited AI tools, advanced analytics, unlimited mock tests, and additional Premium features can choose a subscription plan that best matches their learning needs."),
        ("Can I use Genelis on both mobile and desktop?", "Yes. Genelis is accessible through modern web browsers on desktops, laptops, tablets, and most smartphones. This flexibility allows students to continue learning, revising, or practising from almost anywhere while maintaining the same connected learning experience across devices."),
        ("What makes Genelis different from tuition and other learning apps?", "Many students use separate resources for notes, practice questions, mock tests, revision, analytics, and performance tracking. Genelis brings these learning activities together into one connected platform. Through the Genelis Learning System, students can move naturally from learning concepts to practising questions, testing understanding, analysing performance, improving weaker areas, and reinforcing learning. Features such as the Wrong Question Notebook, Weak Area Detection, AI Study Coach, and Reattempt Mocks are designed to help students study more purposefully instead of simply spending more time studying."),
        ("Does Genelis provide AI-generated notes and summaries?", "Yes. Genelis generates structured AI-powered notes and chapter summaries to help students revise important concepts more efficiently. These notes are designed to complement classroom learning and NCERT textbooks by presenting key ideas in a concise, organised, and easy-to-review format. Students can also use the platform to revisit topics repeatedly as they progress through the Genelis Learning System."),
        ("Can Genelis help students prepare for board examinations?", "Genelis is designed to support long-term CBSE board exam preparation through structured revision, chapter-wise practice, mock tests, AI-powered performance analysis, and personalised learning recommendations. Features such as Weak Area Detection, Wrong Question Notebook, and Reattempt Mocks help students focus on concepts that require additional attention. While academic success ultimately depends on a student's effort, consistency, and understanding, Genelis aims to provide the tools, guidance, and insights needed to help students prepare with greater confidence and clarity."),
    ],
)

FAQ_DATA["learning_system"] = section(
    "Questions About the Genelis Learning System",
    "The Genelis Learning System is designed to make studying more structured, personalised, and effective. Instead of treating learning as separate tasks, it brings notes, practice, mock tests, performance analysis, revision, and AI guidance together into one connected experience.",
    "Ready to experience the Genelis Learning System?",
    "See how AI-powered notes, structured practice, mock tests, performance insights, and personalised guidance come together to help you learn more effectively.",
    "Start Learning",
    "learning_system_final",
    [
        ("What is the Genelis Learning System?", "The Genelis Learning System is a structured learning framework that guides students through every stage of preparation—from understanding concepts and practising questions to analysing performance, strengthening weak areas, and revising effectively. Rather than relying on multiple disconnected resources, it combines AI-powered notes, chapter-wise practice, mock tests, performance insights, and personalised guidance into one connected learning experience. The objective is to help students study with greater clarity, consistency, and confidence."),
        ("How does the Genelis Learning System work?", "The learning journey follows a structured sequence: Learn, Practice, Test, Analyse, Improve, and Reinforce. Students begin by building conceptual understanding through AI-generated notes and explanations, apply what they have learned through practice questions, evaluate their understanding with mock tests, review their performance using analytics, strengthen weaker areas through personalised recommendations, and reinforce concepts through continuous revision. This cycle helps transform learning into an ongoing process rather than a one-time activity."),
        ("How are AI notes generated?", "Genelis AI creates structured notes based on the selected chapter or topic while keeping the content aligned with the latest available CBSE and NCERT curriculum. The notes focus on explaining important concepts, highlighting key points, and presenting information in a clear and organised format. They are designed to support classroom learning and revision, helping students review topics more efficiently without replacing their textbooks or teacher's guidance."),
        ("Does Genelis create personalised study plans?", "Yes. As students interact with the platform, Genelis AI analyses learning patterns, performance, and progress to provide personalised recommendations. Instead of suggesting the same revision schedule for every learner, the platform prioritises topics that may require additional attention, helping students use their study time more effectively while maintaining balanced preparation across subjects."),
        ("How does Genelis identify weak areas?", "Genelis continuously analyses practice sessions, mock test performance, and learning behaviour to identify concepts that require further attention. Rather than focusing only on overall marks, the platform looks for recurring mistakes and patterns across chapters. These insights help students understand where they need additional revision and allow them to focus on improving concepts before moving forward."),
        ("How are mock tests generated?", "Genelis offers chapter-wise and subject-wise mock tests designed around the latest CBSE exam patterns. Questions are selected to encourage conceptual understanding and application rather than simple memorisation. After each attempt, students receive performance insights that highlight strengths, identify weaker topics, and support more focused revision for future attempts."),
        ("What is the Wrong Question Notebook?", "The Wrong Question Notebook is a revision tool that automatically collects questions answered incorrectly during practice sessions and mock tests. Instead of repeating the entire syllabus, students can revisit their previous mistakes in one place, understand why the correct answer is right, and strengthen concepts that need additional practice. This encourages continuous improvement through targeted revision."),
        ("Can I reattempt mock tests after improving?", "Yes. Genelis allows students to reattempt eligible mock tests after completing additional study and revision. Reattempting helps students measure improvement over time, reinforce concepts, and build confidence by comparing their performance across multiple attempts rather than relying on a single score."),
        ("How does the AI Study Coach support learning?", "The AI Study Coach provides guidance throughout the learning journey by helping students decide what to study next, suggesting revision priorities, encouraging consistent learning habits, and supporting preparation based on individual progress. Instead of replacing independent thinking, it acts as a learning companion that helps students make more informed study decisions."),
        ("How does the Genelis Learning System help improve exam preparation?", "Effective exam preparation requires more than completing the syllabus. The Genelis Learning System combines conceptual learning, structured practice, mock testing, performance analysis, personalised recommendations, and continuous revision into one connected process. By helping students identify weaker areas, revisit previous mistakes, and study more strategically, the platform supports consistent progress while encouraging deeper understanding and long-term retention."),
    ],
)

FAQ_DATA["pricing"] = section(
    "Subscription & Pricing Questions",
    "Choosing the right learning plan is an important decision. Below are answers to some of the most common questions about Genelis subscriptions, Premium features, payments, billing, and account management to help you make an informed choice.",
    "Still deciding which plan is right for you?",
    "Start with the Free Plan and experience how the Genelis Learning System supports smarter learning through AI-powered notes, structured practice, mock tests, and personalised learning insights. When you're ready, upgrading to Premium is just a few clicks away.",
    "Start Learning",
    "pricing_free",
    [
        ("What is included in the Free Plan?", "The Free Plan allows students to explore the core Genelis experience before deciding whether to upgrade. It includes access to selected AI-powered learning features, limited AI notes, AI doubts, chapter-wise practice, mock tests, personalised learning insights, and the Genelis Learning System. The Free Plan is designed to help students understand how the platform works while providing meaningful support for everyday learning."),
        ("What additional features are included in the Premium Plan?", "The Premium Plan unlocks the complete Genelis experience with higher usage limits and unrestricted access to learning tools. Depending on the selected plan, students can enjoy unlimited AI Notes, unlimited AI Doubts, unlimited chapter-wise and subject-wise mock tests, Wrong Question Notebook, Reattempt Mocks, PDF downloads, advanced learning features, and future Premium enhancements as they become available. Premium is designed for students who want uninterrupted access throughout their academic preparation."),
        ("Can I upgrade my subscription at any time?", "Yes. Students can upgrade from the Free Plan to a Premium Plan whenever they choose. Once payment is successfully completed, Premium features are activated automatically for the subscribed account, allowing students to continue learning without interruption."),
        ("Can I switch from a Monthly Plan to an Annual Plan?", "Yes. Students who begin with a Monthly Plan can upgrade to the Annual Plan whenever they wish. The Annual Plan is designed for students preparing over a longer period and provides uninterrupted access to Premium features throughout the subscription period."),
        ("Which payment methods does Genelis support?", "Genelis supports secure online payments through trusted payment partners. Depending on availability, students may be able to pay using UPI, debit cards, credit cards, net banking, and other supported digital payment methods. Available payment options are displayed during the checkout process."),
        ("Are subscriptions renewed automatically?", "Subscription renewal depends on the payment settings and plan selected during purchase. Where automatic renewal is available, students will continue receiving Premium access unless the subscription is cancelled before the renewal date. Any applicable renewal information will be clearly presented during the subscription process."),
        ("Is my payment information secure?", "Yes. Genelis does not store sensitive payment information such as complete card details or banking credentials. Payments are processed through trusted payment gateways that use industry-standard security measures to help protect financial transactions. Students should always ensure they are completing payments through the official Genelis website."),
        ("What happens if my payment is successful but Premium isn't activated immediately?", "In most cases, Premium access is activated automatically within a few moments after a successful payment. If there is a temporary delay due to payment processing or network issues, please allow a short period for the transaction to complete before refreshing your account. If your payment has been successfully debited but Premium access is still unavailable after a reasonable amount of time, please contact the Genelis Support Team at support@genelis.in with your registered email address, Payment ID, Order ID, and any relevant transaction details. To ensure the safety of your account, Premium subscriptions are activated only after successful payment verification."),
        ("Can I request a refund?", "Refund eligibility depends on the circumstances and is governed by the Genelis Refund & Cancellation Policy. Students who experience payment-related issues or believe they qualify for a refund can contact the Genelis support team with the relevant transaction details. Each request is reviewed in accordance with the applicable policy."),
        ("Will I automatically receive new Premium features?", "Yes. As Genelis continues to introduce new Premium features and improvements, eligible subscribers will generally receive access to those features as part of their active subscription unless otherwise stated. This allows students to benefit from ongoing platform enhancements without requiring a separate purchase for every new feature."),
        ("Why should I choose Premium over the Free Plan?", "The Free Plan is ideal for exploring Genelis and experiencing its core learning capabilities. Premium is intended for students who want uninterrupted access to the complete learning experience throughout the academic year. With unlimited AI-powered tools, comprehensive mock tests, structured revision support, advanced learning features, and personalised insights, Premium enables students to study more consistently while making full use of the Genelis Learning System."),
    ],
)

FAQ_DATA["about"] = section(
    "About Genelis",
    "Genelis was created with a simple belief: learning should be more personalised, structured, and accessible for every student. Below are answers to some of the most common questions about our mission, values, approach to AI, and the vision behind the platform.",
    "Have more questions about Genelis?",
    "The best way to understand how Genelis supports learning is to experience it yourself. Explore the platform, discover the Genelis Learning System, and see how AI can help make learning more structured, personalised, and effective.",
    "Start Learning",
    "about_primary",
    [
        ("Why was Genelis created?", "Genelis was created to simplify the way students learn. Many learners rely on multiple resources for notes, practice questions, mock tests, revision, and performance tracking, making preparation fragmented and time-consuming. Genelis brings these essential learning activities together into one connected platform, helping students stay organised while making better use of their study time. Our goal is to support meaningful learning rather than simply increasing the amount of content students consume."),
        ("What is the mission of Genelis?", "Our mission is to make quality learning more personalised, accessible, and effective through responsible use of Artificial Intelligence. We aim to help students develop stronger conceptual understanding, better study habits, and greater confidence by providing tools that support every stage of their learning journey rather than focusing only on examination outcomes."),
        ("Is Genelis an educational institution?", "No. Genelis is a technology platform that supports learning through AI-powered educational tools and study resources. It is not a school, college, coaching institute, examination authority, or certification body. Students should continue to learn from their teachers, schools, textbooks, and official educational resources while using Genelis as a complementary learning companion."),
        ("How does Genelis use Artificial Intelligence responsibly?", "Artificial Intelligence is designed to support—not replace—learning. Genelis AI helps students generate notes, understand concepts, identify weak areas, receive personalised recommendations, and organise revision more effectively. While every effort is made to provide accurate educational assistance, students are encouraged to verify important information using their textbooks, teachers, and official CBSE or NCERT resources whenever appropriate."),
        ("Does Genelis replace teachers or coaching?", "No. Genelis is designed to complement classroom learning rather than replace teachers or coaching. Teachers provide guidance, experience, and personal interaction that technology cannot replicate. Genelis supports this process by helping students revise independently, practise regularly, monitor their progress, and make better-informed decisions about what to study next."),
        ("What makes Genelis different from other learning platforms?", "Genelis combines multiple stages of learning into one connected experience through the Genelis Learning System. Instead of switching between separate tools for notes, revision, mock tests, analytics, and performance tracking, students can manage their learning journey within a single platform. AI-powered insights help students focus on understanding concepts, identifying weaker areas, and building consistent study habits over time."),
        ("How do you ensure the quality of educational content?", "Educational content is developed with the objective of supporting the latest available CBSE and NCERT curriculum. AI-generated content is continually refined, while the platform is regularly improved based on user feedback, curriculum updates, and ongoing evaluation. Since AI-generated responses may occasionally contain inaccuracies, students should use Genelis alongside official educational resources and classroom instruction."),
        ("How can I share feedback or suggestions?", "We believe continuous improvement begins with listening to our users. Students, parents, educators, and other users are encouraged to share feedback, suggestions, feature requests, or report issues through the in-platform Feedback section or by contacting the Genelis Support Team. User feedback plays an important role in helping us improve both the platform and the overall learning experience."),
        ("Is Genelis continuously improving?", "Yes. Education and technology continue to evolve, and so does Genelis. We regularly introduce improvements, refine AI capabilities, enhance learning features, strengthen platform performance, and respond to curriculum changes where appropriate. Our objective is to build a platform that continues to grow alongside the needs of students and educators."),
        ("What is the long-term vision for Genelis?", "Our long-term vision is to build an intelligent learning platform that helps students learn with greater confidence, independence, and understanding throughout their academic journey. We aim to combine responsible Artificial Intelligence with thoughtful educational design to make learning more personalised, engaging, and accessible while continually improving the experience based on real student needs."),
    ],
)

FAQ_DATA["contact"] = section(
    "Need Help? Start Here",
    "Whether you have a question about Genelis, need assistance with your account, want to report a technical issue, or simply wish to share feedback, we're here to help. Below are answers to some of the most common support-related questions.",
    "Still need assistance?",
    "We're committed to providing a helpful, respectful, and transparent support experience. If you couldn't find the answer you were looking for, please get in touch and we'll do our best to assist you.",
    "Email Support",
    "Contact Support",
    [
        ("How can I contact Genelis?", "You can contact the Genelis Support Team by emailing support@genelis.in. Whether you have questions about your account, subscriptions, technical issues, AI-generated content, or general enquiries, our team will make reasonable efforts to assist you as promptly as possible."),
        ("What are your support hours?", "Our support team reviews enquiries during regular business hours. While response times may vary depending on the nature and volume of requests, we aim to respond as quickly as reasonably possible. Some complex technical, billing, or legal matters may require additional investigation before a complete response can be provided."),
        ("How long does it take to receive a response?", "We strive to acknowledge enquiries within a reasonable timeframe and respond as quickly as possible. Simpler questions may be resolved sooner, while technical investigations, payment-related matters, or requests requiring additional verification may take longer. We appreciate your patience while we work to resolve each request thoroughly."),
        ("How do I report a technical issue?", "If you encounter a technical problem while using Genelis, please contact us at support@genelis.in with as much detail as possible. Including your registered email address, device information, browser, screenshots, error messages, and the steps that led to the issue helps us investigate and resolve the problem more efficiently."),
        ("How can I report incorrect AI-generated content?", "Although Genelis AI is designed to generate helpful educational content, AI-generated responses may occasionally contain inaccuracies or require clarification. If you identify content that appears incorrect, outdated, or misleading, please report it through the in-platform Feedback section or by emailing support@genelis.in. Your feedback helps us improve both the quality and reliability of the platform."),
        ("How do I report a payment or subscription issue?", "If you experience a payment failure, duplicate charge, delayed subscription activation, or any other billing-related concern, please contact the Genelis Support Team with your registered email address, Payment ID, Order ID, and any relevant transaction details. Providing complete information allows us to investigate the issue and assist you more efficiently."),
        ("Can I submit feature requests or suggestions?", "Yes. We welcome ideas from students, parents, and educators. If there is a feature you would like to see on Genelis or you have suggestions for improving the platform, you can submit them through the in-platform Feedback section or by contacting us directly. Many platform improvements are inspired by valuable feedback from our user community."),
        ("How can I report a security issue?", "If you believe you have discovered a security vulnerability or suspect unauthorised activity affecting Genelis, please contact us immediately at support@genelis.in and include Security Issue in the subject line of your email. Providing a detailed description of the issue will help us investigate and take appropriate action as quickly as possible."),
        ("Where can I submit feedback or raise a grievance?", "Genelis provides multiple ways to share feedback, report concerns, or raise formal grievances. Users may use the in-platform Feedback section to submit suggestions, feature requests, technical issues, or educational content concerns. For formal grievances, users may also contact the designated Grievance Officer through the contact details provided in our Grievance Redressal Policy."),
        ("Who should I contact regarding legal, copyright, or privacy concerns?", "For questions relating to copyright, intellectual property, privacy, data protection, or other legal matters, please contact the Genelis Support Team at support@genelis.in with complete details of your request. Where appropriate, your enquiry will be directed to the relevant team for review and response in accordance with our applicable policies."),
    ],
)

FAQ_DATA["classes"] = section(
    "Questions About Learning with Genelis",
    "Choosing the right learning platform is easier when you know what to expect. Below are answers to common questions about the classes, subjects, learning resources, and study experience available through Genelis.",
    "Ready to start your learning journey?",
    "Choose your class, explore AI-powered learning resources, and experience how the Genelis Learning System helps you learn, practise, analyse, and improve with greater confidence.",
    "Choose Your Class",
    "classes_primary",
    [
        ("Which classes are supported by Genelis?", "Genelis is currently designed for students studying in CBSE Classes 9, 10, 11, and 12. The platform provides class-specific learning resources that are organised according to the latest available NCERT curriculum, helping students prepare for school examinations, board exams, and everyday learning with a structured and personalised approach."),
        ("Which subjects are available on Genelis?", "Genelis supports the major academic subjects prescribed under the CBSE curriculum for each class. Depending on the selected class, students can access learning resources for subjects such as Mathematics, Science, Physics, Chemistry, Biology, Social Science, English, Accountancy, Business Studies, Economics, Political Science, History, Geography, and others where applicable. Subject availability continues to expand as the platform grows."),
        ("Does Genelis cover the complete NCERT syllabus?", "Genelis is designed to align with the latest available CBSE and NCERT curriculum. Learning resources are organised chapter-wise to support complete syllabus coverage while making revision, practice, and progress tracking easier. As official curriculum updates become available, the platform aims to incorporate those changes to keep learning relevant and up to date."),
        ("Are AI Notes available for every chapter?", "Students can generate AI-powered notes for supported chapters across available subjects. These notes summarise important concepts, definitions, formulas, and key ideas in a structured format that complements classroom learning and NCERT textbooks. AI Notes are designed to support efficient revision rather than replace official learning resources."),
        ("Can I practise chapter-wise and subject-wise?", "Yes. Genelis allows students to study individual chapters as well as complete subjects. Chapter-wise learning helps students strengthen specific concepts, while subject-wise practice and mock tests provide a broader assessment of overall preparation. This flexibility allows students to study according to their own learning goals and schedule."),
        ("Does Genelis provide mock tests for every class?", "Yes. Mock tests are available across supported classes, helping students evaluate their understanding through structured assessments. Depending on the selected plan, students can attempt chapter-wise and subject-wise mock tests, review their performance, identify weaker areas, and continue improving through the Genelis Learning System."),
        ("Is the learning experience personalised?", "Yes. Genelis AI analyses learning activity and performance to provide personalised recommendations throughout the learning journey. Rather than presenting identical learning paths to every student, the platform helps prioritise topics that require additional attention, encouraging more focused and efficient preparation."),
        ("Can students monitor their academic progress?", "Yes. Genelis includes performance analytics that help students understand how they are progressing over time. By reviewing practice sessions, mock test results, and learning activity, students can identify strengths, recognise weaker areas, and make more informed decisions about where to focus their revision efforts."),
        ("Can I switch between classes if needed?", "Students can access learning resources according to the classes supported by their account and subscription. This allows flexibility for learners who wish to explore different classes where applicable, while ensuring that study material remains organised according to the selected curriculum."),
        ("Is Genelis suitable for both school exams and board exams?", "Yes. Genelis is designed to support students throughout the academic year, whether they are preparing for regular school assessments or CBSE board examinations. Through AI-powered notes, structured practice, mock tests, personalised guidance, and continuous performance analysis, the platform helps students build stronger understanding and maintain consistent preparation over time."),
    ],
)

FAQ_DATA["blog"] = section(
    "About the Genelis Blog",
    "The Genelis Blog is designed to help students, parents, and educators understand better study methods, exam preparation strategies, AI-powered learning, and CBSE-focused academic planning.",
    "Want to study beyond the blog?",
    "Explore Genelis to move from reading study tips to actually learning, practising, testing, analysing, and improving through one connected AI-powered workspace.",
    "Start Learning",
    "blog_primary",
    [
        ("What topics does the Genelis Blog cover?", "The Genelis Blog covers topics related to CBSE learning, study strategies, exam preparation, AI-powered education, revision methods, productivity, and better learning habits. The goal is to provide useful guidance that supports students in making their preparation more structured and effective."),
        ("How often are new articles published?", "New articles are published as Genelis expands its learning resources and content strategy. The focus is on quality rather than volume, so each article is designed to provide practical value for students, parents, or educators instead of simply adding more content."),
        ("Are blog articles based on the latest CBSE syllabus?", "Where an article discusses CBSE classes, subjects, or exam preparation, the content is written with the latest available CBSE and NCERT curriculum in mind. Students should still refer to official CBSE updates, NCERT textbooks, and school guidance for final academic confirmation."),
        ("Can students rely on these articles for exam preparation?", "The blog is designed to support exam preparation by explaining study methods, revision strategies, and learning approaches. It should be used as a helpful guide alongside textbooks, classroom teaching, practice questions, mock tests, and official curriculum resources."),
        ("Does the blog include AI-powered study strategies?", "Yes. Some blog articles explain how students can use AI-powered learning tools responsibly for notes, revision, weak area detection, practice planning, and exam preparation. The focus is on using AI to support understanding and consistency rather than replacing effort or independent thinking."),
        ("Are the study tips suitable for board exams?", "Many Genelis Blog articles are designed with CBSE board exam preparation in mind, especially for Classes 10 and 12. These articles may cover revision planning, mock test strategy, time management, common mistakes, and ways to strengthen conceptual understanding before exams."),
        ("Can parents also benefit from the blog?", "Yes. Parents can use the blog to better understand modern learning challenges, AI-powered education, exam preparation pressure, and how structured study tools can support students. The content is written to be accessible, practical, and useful for both learners and their families."),
        ("How can I stay updated with new blog posts?", "You can regularly visit the Genelis Blog for new articles and learning resources. As Genelis grows, additional update channels such as social media, email updates, or in-platform notifications may be introduced to help students and parents stay informed."),
    ],
)

def class_section(class_key, heading, intro, cta_heading, cta_text, items):
    FAQ_DATA[class_key] = section(heading, intro, cta_heading, cta_text, "Start Learning", "class_detail_primary", items)

class_section("class_9", "CBSE Class 9 FAQs", "Class 9 is an important step in a student's academic journey, introducing more advanced concepts and greater independence in learning. Building strong fundamentals at this stage helps students prepare for future classes with confidence.", "Build a strong foundation for future success.", "Explore AI-powered notes, structured learning, chapter-wise practice, mock tests, and personalised learning insights through the Genelis Learning System—designed to help you build confidence from Class 9 onwards.", [
    ("Is Genelis suitable for CBSE Class 9 students?", "Yes. Genelis is designed to support CBSE Class 9 students by providing AI-powered notes, structured chapter-wise learning, practice questions, mock tests, personalised learning insights, and performance analytics. Whether you're beginning a new chapter or revising for school examinations, the platform helps make learning more organised, engaging, and effective throughout the academic year."),
    ("Does Genelis cover the complete CBSE Class 9 syllabus?", "Genelis is designed around the latest available CBSE curriculum and NCERT textbooks for Class 9. Learning resources are organised chapter-wise across supported subjects, making it easier for students to study systematically, revise concepts, and monitor their progress. As official curriculum updates become available, the platform aims to reflect those changes to ensure learning remains accurate and relevant."),
    ("Can I generate AI Notes for every Class 9 chapter?", "Students can generate AI-powered notes for supported Class 9 chapters across available subjects. These notes summarise important concepts, definitions, formulas, and key learning points in a clear and structured format. They are designed to complement classroom teaching and NCERT textbooks while helping students revise more efficiently and understand concepts with greater clarity."),
    ("How does Genelis help students build strong study habits?", "Developing consistent study habits is one of the most valuable skills students can build during Class 9. The Genelis Learning System encourages students to learn concepts, practise regularly, test their understanding, analyse their progress, improve weaker areas, and reinforce learning through revision. Following this structured approach helps students stay organised while building confidence and discipline throughout the academic year."),
    ("How do Class 9 mock tests work?", "Genelis provides chapter-wise and subject-wise mock tests that allow students to evaluate their understanding as they progress through the syllabus. After each attempt, students receive performance insights that highlight strengths, identify weaker concepts, and recommend areas for further revision. Regular practice helps students become more confident while preparing for school examinations."),
    ("How does Genelis identify my weak areas?", "Genelis AI analyses chapter-wise practice, mock test performance, and learning activity to identify concepts that may require additional attention. Instead of focusing only on marks, the platform looks for recurring mistakes and learning patterns, helping students revise more effectively and strengthen concepts before moving on to new topics."),
    ("Can Genelis help me prepare for Class 10?", "Yes. Class 9 provides the academic foundation for many topics that students will encounter in Class 10. By encouraging conceptual understanding, regular revision, and consistent practice, Genelis helps students develop learning habits and confidence that support a smoother transition into the next stage of their academic journey."),
    ("What is the Wrong Question Notebook and how does it help?", "The Wrong Question Notebook automatically stores questions answered incorrectly during practice sessions and mock tests. Instead of repeating the entire syllabus, students can revisit previous mistakes, understand the correct approach, and strengthen concepts that need additional practice. This targeted revision helps improve understanding while reducing repeated errors over time."),
    ("Can I study at my own pace with Genelis?", "Yes. Every student learns differently, and Genelis is designed to support individual learning styles. Students can study chapter-wise, revisit difficult concepts whenever needed, practise at their own pace, and receive personalised recommendations from Genelis AI based on their learning progress and performance."),
    ("How does the Genelis Learning System help Class 9 students?", "The Genelis Learning System combines AI-powered notes, structured learning, chapter-wise practice, mock tests, performance analytics, personalised learning recommendations, and continuous revision into one connected experience. By helping students understand concepts, identify weaker areas, revisit previous mistakes, and improve consistently, the platform encourages stronger learning habits that support long-term academic success."),
])

class_section("class_10", "CBSE Class 10 FAQs", "Class 10 is an important milestone in every student's academic journey. Whether you're preparing for school assessments or the CBSE Board Examination, having the right study resources and a structured learning approach can make a significant difference.", "Ready to prepare for CBSE Class 10 with confidence?", "Explore AI-powered notes, structured revision, mock tests, personalised learning insights, and the Genelis Learning System—all designed to help you study smarter throughout the academic year.", [
    ("Is Genelis suitable for CBSE Class 10 students?", "Yes. Genelis is specifically designed to support CBSE Class 10 students through every stage of their preparation. Whether you're learning a chapter for the first time, revising before an exam, or preparing for the board examinations, the platform provides AI-powered notes, structured practice, mock tests, personalised learning insights, and performance analysis to help you study with greater clarity and consistency throughout the academic year."),
    ("Does Genelis cover the complete CBSE Class 10 syllabus?", "Genelis is designed around the latest available CBSE curriculum and NCERT textbooks for Class 10. Learning resources are organised chapter-wise across supported subjects, making it easier to study individual topics, revise important concepts, and prepare systematically. As official syllabus updates become available, the platform aims to keep its educational content aligned with the latest academic requirements."),
    ("Can I generate AI Notes for every Class 10 chapter?", "Students can generate AI-powered notes for supported Class 10 chapters across available subjects. These notes summarise important concepts, definitions, formulas, examples, and revision points in a structured format that complements classroom teaching and NCERT textbooks. They are designed to make revision more efficient while encouraging students to build a deeper conceptual understanding."),
    ("How do Class 10 mock tests work?", "Genelis provides chapter-wise and subject-wise mock tests designed to reflect the style and learning objectives of the CBSE curriculum. Students can attempt mock tests to evaluate their understanding, identify areas that need improvement, and monitor their progress over time. Detailed performance insights help students revise more strategically instead of relying only on overall scores."),
    ("Can Genelis help improve my board exam preparation?", "Genelis is designed to support long-term preparation rather than last-minute learning. Through AI-generated notes, structured revision, regular practice, mock tests, personalised recommendations, and continuous performance analysis, students can prepare more consistently throughout the year. While examination results always depend on individual effort and understanding, the platform helps students build stronger preparation habits and greater confidence before the board examinations."),
    ("How does Genelis identify my weak areas?", "Genelis AI analyses learning activity, practice sessions, and mock test performance to identify concepts that may require additional attention. Instead of focusing only on marks, the platform looks for recurring mistakes and learning patterns to recommend more focused revision. This allows students to spend more time improving concepts that have the greatest impact on their overall preparation."),
    ("Can I revise chapter-wise before my exams?", "Yes. Every supported chapter is organised individually so students can revise topics according to their own study plan. AI Notes, chapter-wise practice, mock tests, and performance insights work together to help students strengthen one concept at a time while maintaining steady progress across the entire syllabus."),
    ("Can I prepare for CBSE Class 10 without coaching?", "Every student learns differently, and there is no single preparation method that works for everyone. Genelis is designed to support independent learning by providing structured resources, AI-powered guidance, chapter-wise practice, and continuous performance insights. Many students may find these tools helpful for self-study, while others may choose to use Genelis alongside classroom teaching or coaching depending on their individual learning needs."),
    ("Does Genelis include previous-year question practice?", "Genelis aims to help students practise questions that reflect the concepts and learning outcomes expected under the CBSE curriculum. Where available, students may also benefit from additional question practice designed to strengthen conceptual understanding and exam readiness. The platform continues to expand its learning resources as new educational content is introduced."),
    ("How does the Genelis Learning System help Class 10 students?", "The Genelis Learning System combines learning, practice, testing, analysis, improvement, and revision into one connected experience. Instead of switching between multiple resources, students can generate AI Notes, practise chapter-wise questions, attempt mock tests, review performance analytics, identify weaker areas, revisit mistakes through the Wrong Question Notebook, and receive personalised learning recommendations within a single platform. This structured approach helps students study more efficiently while developing stronger understanding and greater confidence throughout their Class 10 journey."),
])

class_section("class_11", "CBSE Class 11 FAQs", "Class 11 marks the beginning of advanced academic learning, where building strong concepts becomes more important than memorising answers. Whether you're adjusting to a new syllabus, preparing for school examinations, or laying the foundation for future board and competitive exams, Genelis helps you learn with greater structure, clarity, and confidence.", "Build stronger concepts from the very beginning.", "Discover how the Genelis Learning System combines AI-powered notes, structured practice, mock tests, and personalised learning insights to help you succeed throughout Class 11 and beyond.", [
    ("Is Genelis suitable for CBSE Class 11 students?", "Yes. Genelis is designed to support CBSE Class 11 students through AI-powered notes, structured chapter-wise learning, mock tests, personalised learning insights, and performance analytics. Since Class 11 introduces more advanced concepts across subjects, the platform focuses on helping students develop strong fundamentals while encouraging consistent study habits throughout the academic year."),
    ("Does Genelis cover the complete CBSE Class 11 syllabus?", "Genelis is designed around the latest available CBSE curriculum and NCERT textbooks for Class 11. Learning resources are organised chapter-wise across supported subjects, allowing students to study systematically, revise important concepts, and monitor their progress as they complete the syllabus. The platform continues to evolve alongside official curriculum updates wherever applicable."),
    ("Can I generate AI Notes for every Class 11 chapter?", "Students can generate AI-powered notes for supported Class 11 chapters across available subjects. These notes highlight important concepts, definitions, formulas, and key learning points in a structured format that supports classroom teaching and NCERT textbooks. They are designed to simplify revision while helping students understand concepts rather than simply memorising information."),
    ("How does Genelis help build strong concepts in Class 11?", "Class 11 introduces topics that form the foundation for Class 12 and many competitive examinations. The Genelis Learning System encourages students to first understand concepts through AI Notes and structured explanations before reinforcing learning through practice questions, mock tests, personalised recommendations, and continuous revision. This approach helps students develop confidence by strengthening conceptual understanding step by step."),
    ("How do Class 11 mock tests work?", "Genelis provides chapter-wise and subject-wise mock tests that allow students to regularly assess their understanding throughout the year. After every attempt, students receive detailed performance insights that help identify strengths, recognise weaker concepts, and plan more focused revision. This continuous evaluation supports steady academic improvement rather than relying only on end-of-term examinations."),
    ("How does Genelis identify my weak areas?", "Genelis AI analyses learning activity, practice sessions, and mock test performance to identify concepts that require additional attention. Instead of focusing only on scores, the platform identifies recurring mistakes and learning patterns to recommend areas where additional study may be beneficial, helping students improve more efficiently over time."),
    ("Can Genelis support preparation for future competitive exams?", "While Genelis is primarily designed for CBSE Class 11 learning, developing strong conceptual understanding during this stage also benefits students preparing for future competitive examinations. By helping students build solid fundamentals, maintain consistent revision, and identify weaker topics early, the platform supports long-term academic preparation alongside regular school studies."),
    ("What is the Wrong Question Notebook and how does it help?", "The Wrong Question Notebook automatically stores questions answered incorrectly during practice sessions and mock tests. Instead of repeating the entire syllabus, students can revisit previous mistakes, understand the correct approach, and strengthen concepts that need additional attention. This focused revision helps reduce repeated errors while improving long-term retention."),
    ("Can I study at my own pace with Genelis?", "Yes. Every student learns differently. Genelis allows students to progress according to their own learning pace while using AI-powered notes, chapter-wise practice, mock tests, and personalised recommendations to support consistent improvement. Students can spend additional time on difficult topics while continuing to monitor their overall progress across subjects."),
    ("How does the Genelis Learning System help Class 11 students?", "The Genelis Learning System combines learning, practice, testing, analysis, improvement, and revision into one connected experience. Students can generate AI Notes, practise chapter-wise questions, attempt mock tests, analyse their performance, identify weaker concepts, revisit mistakes through the Wrong Question Notebook, and receive personalised learning recommendations—all within a single platform. This structured approach helps students build the strong conceptual foundation needed for future academic success."),
])

class_section("class_12", "CBSE Class 12 FAQs", "Class 12 is one of the most important years in a student's academic journey. Along with preparing for the CBSE Board Examination, many students are also balancing entrance exam preparation and planning their next academic step.", "Ready to prepare for CBSE Class 12 with confidence?", "Explore AI-powered notes, chapter-wise practice, structured revision, mock tests, and personalised learning insights through the Genelis Learning System—all designed to help you study smarter throughout your Class 12 journey.", [
    ("Is Genelis suitable for CBSE Class 12 students?", "Yes. Genelis is designed to help CBSE Class 12 students prepare with greater confidence through structured learning, AI-powered notes, chapter-wise practice, mock tests, personalised learning insights, and performance analytics. Whether you're revising a single chapter or preparing for the board examinations, the platform helps organise your preparation while encouraging consistent learning throughout the academic year."),
    ("Does Genelis cover the complete CBSE Class 12 syllabus?", "Genelis is designed around the latest available CBSE curriculum and NCERT textbooks for Class 12. Learning resources are organised chapter-wise across supported subjects, allowing students to study systematically, revise concepts efficiently, and prepare according to the prescribed syllabus. As official curriculum updates become available, the platform aims to reflect those changes to keep learning relevant and aligned with current academic requirements."),
    ("Can I generate AI Notes for every Class 12 chapter?", "Students can generate AI-powered notes for supported Class 12 chapters across available subjects. These notes summarise important concepts, formulas, definitions, diagrams where applicable, and revision points in a structured format that complements classroom teaching and NCERT textbooks. They are intended to simplify revision while helping students strengthen conceptual understanding before examinations."),
    ("How do Class 12 mock tests work?", "Genelis provides chapter-wise and subject-wise mock tests designed to help students evaluate their preparation throughout the year. After every attempt, students receive performance insights that highlight strengths, identify weaker concepts, and support more focused revision. Regular mock testing also helps students become more familiar with exam-style questions and improve confidence before the board examinations."),
    ("Can Genelis help me prepare for both board exams and competitive exams?", "Genelis is primarily designed to support CBSE Class 12 learning and board examination preparation. Because strong conceptual understanding is essential for many competitive examinations, the platform also helps students build a solid academic foundation through structured learning, continuous practice, and personalised revision. Students preparing for specific competitive exams should continue to use resources designed for those examinations alongside their board preparation."),
    ("How does Genelis identify my weak areas?", "Genelis AI analyses learning activity, chapter-wise practice, and mock test performance to identify concepts that require additional attention. Rather than focusing only on overall marks, the platform looks for recurring mistakes and learning patterns, helping students prioritise revision where it can have the greatest impact on their overall preparation."),
    ("Can I revise chapter-wise before the board examinations?", "Yes. Every supported chapter is organised individually, allowing students to revise according to their own study schedule. AI Notes, chapter-wise practice, mock tests, performance insights, and personalised recommendations work together to help students strengthen concepts systematically while ensuring balanced preparation across the entire syllabus."),
    ("How does the Wrong Question Notebook help Class 12 students?", "The Wrong Question Notebook automatically collects questions answered incorrectly during practice sessions and mock tests. Instead of revising the entire syllabus repeatedly, students can focus specifically on previous mistakes, understand why the correct answer is right, and revisit concepts that require further practice. This targeted revision approach helps improve accuracy and long-term retention."),
    ("Can Genelis support self-study during Class 12?", "Yes. Many students prefer to study independently or supplement classroom learning with additional practice. Genelis supports self-study by bringing AI-powered notes, structured revision, mock tests, personalised learning insights, and progress tracking into one connected platform. Students can learn at their own pace while receiving guidance on what to revise next based on their performance."),
    ("How does the Genelis Learning System help Class 12 students?", "The Genelis Learning System provides a structured approach to preparation by combining conceptual learning, chapter-wise practice, mock tests, performance analytics, personalised recommendations, and continuous revision into one connected experience. Features such as AI Notes, Weak Area Detection, Wrong Question Notebook, and Reattempt Mocks help students strengthen understanding, improve consistency, and prepare more confidently for their board examinations."),
])


def build_faq_schema(faq):
    return {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            {
                "@type": "Question",
                "name": item["question"],
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": item["answer"],
                },
            }
            for item in faq["items"]
        ],
    }
